package server

import (
	"context"
	"crypto/subtle"
	"errors"
	"log/slog"
	"net/http"
	"net/url"
	"strconv"
	"strings"
	"time"

	"nabuauth/internal/config"
	"nabuauth/internal/store"
	"nabuauth/internal/tokens"
)

// SyncApps upserts every app from the config into the client table.
//
// Client secrets are stored as a SHA-256 hash rather than bcrypt: they are
// high-entropy values generated by an operator, not user-chosen passwords, so
// there is nothing to brute-force, and a stable hash keeps the boot-time upsert
// from rewriting the row on every restart.
func SyncApps(ctx context.Context, cfg *config.Config, st *store.Store, log *slog.Logger) error {
	for _, app := range cfg.Apps {
		secretHash := ""
		if secret := app.Secret(); secret != "" {
			secretHash = tokens.HashOpaque(secret)
		} else if !app.Public {
			// Confidential client with no secret in the environment. Registering
			// it anyway would leave an app that can start a login it can never
			// finish, so say so loudly and keep whatever secret is already stored.
			log.Warn("confidential app has no secret in the environment; it cannot complete a token exchange until one is set",
				"app", app.ID, "secret_env", app.SecretEnv)
		}
		if err := st.UpsertClient(ctx, store.Client{
			ClientID:       app.ID,
			Name:           app.Name,
			Description:    app.Description,
			Icon:           app.Icon,
			AppURL:         app.URL,
			Badge:          app.Badge,
			SecretHash:     secretHash,
			RedirectURIs:   app.RedirectURIs,
			Scopes:         app.Scopes,
			IsConfidential: !app.Public,
			IsListed:       !app.Hidden,
		}); err != nil {
			return err
		}
	}
	return nil
}

// ---------------------------------------------------------------- discovery

func (s *Server) handleDiscovery(w http.ResponseWriter, _ *http.Request) {
	iss := s.cfg.Server.Issuer
	scopes := make([]string, 0, len(s.cfg.Scopes))
	for k := range s.cfg.Scopes {
		scopes = append(scopes, k)
	}
	writeJSON(w, http.StatusOK, map[string]any{
		"issuer":                                iss,
		"authorization_endpoint":                iss + "/oauth/authorize",
		"token_endpoint":                        iss + "/oauth/token",
		"userinfo_endpoint":                     iss + "/oauth/userinfo",
		"jwks_uri":                              iss + "/oauth/jwks.json",
		"introspection_endpoint":                iss + "/oauth/introspect",
		"revocation_endpoint":                   iss + "/oauth/revoke",
		"end_session_endpoint":                  iss + "/oauth/logout",
		"scopes_supported":                      scopes,
		"response_types_supported":              []string{"code"},
		"grant_types_supported":                 []string{"authorization_code", "refresh_token", "client_credentials"},
		"subject_types_supported":               []string{"public"},
		"id_token_signing_alg_values_supported": []string{"RS256"},
		"token_endpoint_auth_methods_supported": []string{"client_secret_basic", "client_secret_post", "none"},
		"code_challenge_methods_supported":      []string{"S256", "plain"},
		"claims_supported":                      []string{"sub", "name", "email", "email_verified", "picture", "scope", "client_id"},
	})
}

func (s *Server) handleJWKS(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Cache-Control", "public, max-age=300")
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	// Written directly rather than through writeJSON, which sets no-store: the
	// whole point of a JWKS is that verifiers cache it.
	body := s.keys.JWKS()
	w.WriteHeader(http.StatusOK)
	_ = encodeJSON(w, body)
}

// ---------------------------------------------------------------- authorize

// authRequest is a validated /oauth/authorize query.
type authRequest struct {
	Client          store.Client
	RedirectURI     string
	Scopes          []string
	State           string
	Nonce           string
	CodeChallenge   string
	ChallengeMethod string
	Prompt          string
}

func (s *Server) parseAuthRequest(w http.ResponseWriter, r *http.Request, q url.Values) (authRequest, bool) {
	clientID := q.Get("client_id")
	client, err := s.store.ClientByID(r.Context(), clientID)
	if err != nil {
		// No redirect: an unknown client means we have no verified URI to send
		// the user to, and bouncing to an attacker-supplied one is the bug.
		s.render(w, http.StatusBadRequest, "error.html", map[string]any{
			"Title":   "Unknown application",
			"Message": "No Nabu application is registered with the client id \"" + clientID + "\".",
		})
		return authRequest{}, false
	}
	redirectURI := q.Get("redirect_uri")
	if redirectURI == "" && len(client.RedirectURIs) == 1 {
		redirectURI = client.RedirectURIs[0]
	}
	if !client.AllowsRedirect(redirectURI) {
		s.render(w, http.StatusBadRequest, "error.html", map[string]any{
			"Title":   "Redirect not allowed",
			"Message": "\"" + redirectURI + "\" is not a registered redirect URI for " + client.Name + ".",
		})
		return authRequest{}, false
	}

	req := authRequest{
		Client:          client,
		RedirectURI:     redirectURI,
		State:           q.Get("state"),
		Nonce:           q.Get("nonce"),
		CodeChallenge:   q.Get("code_challenge"),
		ChallengeMethod: q.Get("code_challenge_method"),
		Prompt:          q.Get("prompt"),
	}

	// Past this point the redirect URI is verified, so errors go back to the app
	// as the spec requires.
	if rt := q.Get("response_type"); rt != "code" {
		s.redirectError(w, r, req, "unsupported_response_type", "only response_type=code is supported")
		return authRequest{}, false
	}
	requested := store.SplitList(q.Get("scope"))
	if len(requested) == 0 {
		requested = client.Scopes
	}
	for _, sc := range requested {
		if _, known := s.cfg.Scopes[sc]; !known {
			s.redirectError(w, r, req, "invalid_scope", "unknown scope "+sc)
			return authRequest{}, false
		}
		if !client.AllowsScope(sc) {
			s.redirectError(w, r, req, "invalid_scope", client.Name+" is not allowed to request "+sc)
			return authRequest{}, false
		}
	}
	req.Scopes = requested

	if req.ChallengeMethod == "" && req.CodeChallenge != "" {
		req.ChallengeMethod = "S256"
	}
	if req.ChallengeMethod != "" && req.ChallengeMethod != "S256" && req.ChallengeMethod != "plain" {
		s.redirectError(w, r, req, "invalid_request", "unsupported code_challenge_method")
		return authRequest{}, false
	}
	// A public client holds no secret, so PKCE is the only thing standing
	// between a stolen code and a token.
	if !client.IsConfidential && req.CodeChallenge == "" {
		s.redirectError(w, r, req, "invalid_request", "code_challenge is required for public clients")
		return authRequest{}, false
	}
	return req, true
}

func (s *Server) handleAuthorize(w http.ResponseWriter, r *http.Request) {
	req, ok := s.parseAuthRequest(w, r, r.URL.Query())
	if !ok {
		return
	}

	user, signedIn := s.currentUser(r)
	if !signedIn || req.Prompt == "login" {
		if req.Prompt == "none" {
			s.redirectError(w, r, req, "login_required", "no active session")
			return
		}
		if signedIn {
			s.endSession(w, r)
		}
		http.Redirect(w, r, "/login?next="+url.QueryEscape(r.URL.RequestURI()), http.StatusFound)
		return
	}

	consented, err := s.store.HasConsent(r.Context(), user.ID, req.Client.ClientID, req.Scopes)
	if err != nil {
		s.log.Error("consent lookup", "error", err)
		s.redirectError(w, r, req, "server_error", "could not read consent")
		return
	}
	if consented && req.Prompt != "consent" {
		s.issueCode(w, r, req, user)
		return
	}
	if req.Prompt == "none" {
		s.redirectError(w, r, req, "consent_required", "the user has not approved these scopes")
		return
	}

	s.render(w, http.StatusOK, "consent.html", map[string]any{
		"Title":     "Authorize " + req.Client.Name,
		"User":      user,
		"Client":    req.Client,
		"Scopes":    s.scopeLabels(req.Scopes),
		"CSRF":      s.csrfToken(r),
		"RawScope":  store.JoinList(req.Scopes),
		"Request":   req,
		"CancelURL": req.RedirectURI,
	})
}

// handleAuthorizeDecision processes the consent form.
func (s *Server) handleAuthorizeDecision(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseForm(); err != nil {
		http.Error(w, "bad form", http.StatusBadRequest)
		return
	}
	user, signedIn := s.currentUser(r)
	if !signedIn {
		http.Redirect(w, r, "/login", http.StatusFound)
		return
	}
	if !s.checkCSRF(r) {
		s.render(w, http.StatusForbidden, "error.html", map[string]any{
			"Title":   "Expired form",
			"Message": "This approval form is no longer valid. Start the sign-in again from the application.",
		})
		return
	}
	req, ok := s.parseAuthRequest(w, r, r.PostForm)
	if !ok {
		return
	}
	if r.PostFormValue("approve") != "yes" {
		s.redirectError(w, r, req, "access_denied", "the user declined")
		return
	}
	if err := s.store.SaveConsent(r.Context(), user.ID, req.Client.ClientID, req.Scopes); err != nil {
		s.log.Error("save consent", "error", err)
		s.redirectError(w, r, req, "server_error", "could not record consent")
		return
	}
	s.issueCode(w, r, req, user)
}

// issueCode mints an authorization code and redirects back to the app.
func (s *Server) issueCode(w http.ResponseWriter, r *http.Request, req authRequest, user store.User) {
	code, hash, err := tokens.NewOpaque()
	if err != nil {
		s.log.Error("generate code", "error", err)
		s.redirectError(w, r, req, "server_error", "could not issue a code")
		return
	}
	err = s.store.SaveCode(r.Context(), hash, store.Code{
		ClientID:        req.Client.ClientID,
		UserID:          user.ID,
		RedirectURI:     req.RedirectURI,
		Scopes:          req.Scopes,
		CodeChallenge:   req.CodeChallenge,
		ChallengeMethod: req.ChallengeMethod,
		Nonce:           req.Nonce,
	}, time.Now().Add(s.codeTTL))
	if err != nil {
		s.log.Error("save code", "error", err)
		s.redirectError(w, r, req, "server_error", "could not issue a code")
		return
	}
	q := url.Values{"code": {code}}
	if req.State != "" {
		q.Set("state", req.State)
	}
	http.Redirect(w, r, appendQuery(req.RedirectURI, q), http.StatusFound)
}

func (s *Server) redirectError(w http.ResponseWriter, r *http.Request, req authRequest, code, description string) {
	q := url.Values{"error": {code}, "error_description": {description}}
	if req.State != "" {
		q.Set("state", req.State)
	}
	http.Redirect(w, r, appendQuery(req.RedirectURI, q), http.StatusFound)
}

// appendQuery adds parameters to a URL, preserving any it already carries.
func appendQuery(rawURL string, extra url.Values) string {
	u, err := url.Parse(rawURL)
	if err != nil {
		return rawURL
	}
	q := u.Query()
	for k, vs := range extra {
		for _, v := range vs {
			q.Set(k, v)
		}
	}
	u.RawQuery = q.Encode()
	return u.String()
}

// ---------------------------------------------------------------- token

func (s *Server) handleToken(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseForm(); err != nil {
		oauthError(w, http.StatusBadRequest, "invalid_request", "malformed form body")
		return
	}
	switch r.PostFormValue("grant_type") {
	case "authorization_code":
		s.grantAuthorizationCode(w, r)
	case "refresh_token":
		s.grantRefreshToken(w, r)
	case "client_credentials":
		s.grantClientCredentials(w, r)
	default:
		oauthError(w, http.StatusBadRequest, "unsupported_grant_type", "supported grants: authorization_code, refresh_token, client_credentials")
	}
}

// authenticateClient resolves the client from Basic auth or form fields and
// verifies its secret. A public client authenticates by client_id alone.
func (s *Server) authenticateClient(r *http.Request) (store.Client, error) {
	clientID, secret, ok := r.BasicAuth()
	if !ok {
		clientID, secret = r.PostFormValue("client_id"), r.PostFormValue("client_secret")
	}
	if clientID == "" {
		return store.Client{}, errors.New("client_id is required")
	}
	client, err := s.store.ClientByID(r.Context(), clientID)
	if err != nil {
		return store.Client{}, errors.New("unknown client")
	}
	if !client.IsConfidential {
		return client, nil
	}
	if client.SecretHash == "" {
		return store.Client{}, errors.New("client has no secret configured on the server")
	}
	if subtle.ConstantTimeCompare([]byte(tokens.HashOpaque(secret)), []byte(client.SecretHash)) != 1 {
		return store.Client{}, errors.New("invalid client_secret")
	}
	return client, nil
}

func (s *Server) grantAuthorizationCode(w http.ResponseWriter, r *http.Request) {
	client, err := s.authenticateClient(r)
	if err != nil {
		w.Header().Set("WWW-Authenticate", `Basic realm="nabuauth"`)
		oauthError(w, http.StatusUnauthorized, "invalid_client", err.Error())
		return
	}
	rawCode := r.PostFormValue("code")
	if rawCode == "" {
		oauthError(w, http.StatusBadRequest, "invalid_request", "code is required")
		return
	}
	code, err := s.store.ConsumeCode(r.Context(), tokens.HashOpaque(rawCode))
	if err != nil {
		oauthError(w, http.StatusBadRequest, "invalid_grant", "the code is unknown, expired or already used")
		return
	}
	// A code issued to one app must not be redeemable by another, even when the
	// other app authenticates correctly.
	if code.ClientID != client.ClientID {
		oauthError(w, http.StatusBadRequest, "invalid_grant", "this code was not issued to this client")
		return
	}
	if redirect := r.PostFormValue("redirect_uri"); redirect != "" && redirect != code.RedirectURI {
		oauthError(w, http.StatusBadRequest, "invalid_grant", "redirect_uri does not match the authorization request")
		return
	}
	if !tokens.VerifyPKCE(code.CodeChallenge, code.ChallengeMethod, r.PostFormValue("code_verifier")) {
		oauthError(w, http.StatusBadRequest, "invalid_grant", "code_verifier does not match the code_challenge")
		return
	}

	user, err := s.store.UserByID(r.Context(), code.UserID)
	if err != nil || !user.IsActive {
		oauthError(w, http.StatusBadRequest, "invalid_grant", "the account is no longer active")
		return
	}
	s.writeTokenResponse(w, r, client, user, code.Scopes, code.Nonce)
}

func (s *Server) grantRefreshToken(w http.ResponseWriter, r *http.Request) {
	client, err := s.authenticateClient(r)
	if err != nil {
		w.Header().Set("WWW-Authenticate", `Basic realm="nabuauth"`)
		oauthError(w, http.StatusUnauthorized, "invalid_client", err.Error())
		return
	}
	raw := r.PostFormValue("refresh_token")
	if raw == "" {
		oauthError(w, http.StatusBadRequest, "invalid_request", "refresh_token is required")
		return
	}
	rt, err := s.store.ConsumeRefreshToken(r.Context(), tokens.HashOpaque(raw))
	if err != nil {
		oauthError(w, http.StatusBadRequest, "invalid_grant", "the refresh token is unknown, expired or already used")
		return
	}
	if rt.ClientID != client.ClientID {
		oauthError(w, http.StatusBadRequest, "invalid_grant", "this refresh token was not issued to this client")
		return
	}
	scopes := rt.Scopes
	// A refresh may narrow its scopes but never widen them.
	if requested := store.SplitList(r.PostFormValue("scope")); len(requested) > 0 {
		have := map[string]bool{}
		for _, s := range rt.Scopes {
			have[s] = true
		}
		for _, s := range requested {
			if !have[s] {
				oauthError(w, http.StatusBadRequest, "invalid_scope", "cannot widen scope on refresh")
				return
			}
		}
		scopes = requested
	}
	user, err := s.store.UserByID(r.Context(), rt.UserID)
	if err != nil || !user.IsActive {
		oauthError(w, http.StatusBadRequest, "invalid_grant", "the account is no longer active")
		return
	}
	s.writeTokenResponse(w, r, client, user, scopes, "")
}

// grantClientCredentials issues a service token with no user behind it. This is
// how NabuGate meters usage: it authenticates as itself and names the user in
// the request body.
func (s *Server) grantClientCredentials(w http.ResponseWriter, r *http.Request) {
	client, err := s.authenticateClient(r)
	if err != nil {
		w.Header().Set("WWW-Authenticate", `Basic realm="nabuauth"`)
		oauthError(w, http.StatusUnauthorized, "invalid_client", err.Error())
		return
	}
	if !client.IsConfidential {
		oauthError(w, http.StatusBadRequest, "unauthorized_client", "public clients cannot use client_credentials")
		return
	}
	scopes := client.Scopes
	if requested := store.SplitList(r.PostFormValue("scope")); len(requested) > 0 {
		for _, sc := range requested {
			if !client.AllowsScope(sc) {
				oauthError(w, http.StatusBadRequest, "invalid_scope", client.Name+" is not allowed to request "+sc)
				return
			}
		}
		scopes = requested
	}
	now := time.Now()
	access, err := s.keys.Sign(tokens.Claims{
		Issuer:    s.cfg.Server.Issuer,
		Subject:   "client:" + client.ClientID,
		Audience:  client.ClientID,
		IssuedAt:  now.Unix(),
		ExpiresAt: now.Add(s.accessTTL).Unix(),
		TokenType: "access",
		ClientID:  client.ClientID,
		Scope:     store.JoinList(scopes),
	})
	if err != nil {
		s.log.Error("sign service token", "error", err)
		oauthError(w, http.StatusInternalServerError, "server_error", "could not sign a token")
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{
		"access_token": access,
		"token_type":   "Bearer",
		"expires_in":   int(s.accessTTL.Seconds()),
		"scope":        store.JoinList(scopes),
	})
}

// writeTokenResponse mints the access token, the rotating refresh token and,
// for an openid request, the id_token.
func (s *Server) writeTokenResponse(w http.ResponseWriter, r *http.Request, client store.Client, user store.User, scopes []string, nonce string) {
	now := time.Now()
	subject := strconv.FormatInt(user.ID, 10)
	scopeStr := store.JoinList(scopes)

	access, err := s.keys.Sign(tokens.Claims{
		Issuer:    s.cfg.Server.Issuer,
		Subject:   subject,
		Audience:  client.ClientID,
		IssuedAt:  now.Unix(),
		ExpiresAt: now.Add(s.accessTTL).Unix(),
		TokenType: "access",
		ClientID:  client.ClientID,
		Scope:     scopeStr,
	})
	if err != nil {
		s.log.Error("sign access token", "error", err)
		oauthError(w, http.StatusInternalServerError, "server_error", "could not sign a token")
		return
	}

	body := map[string]any{
		"access_token": access,
		"token_type":   "Bearer",
		"expires_in":   int(s.accessTTL.Seconds()),
		"scope":        scopeStr,
	}

	refreshToken, refreshHash, err := tokens.NewOpaque()
	if err != nil {
		s.log.Error("generate refresh token", "error", err)
		oauthError(w, http.StatusInternalServerError, "server_error", "could not issue a refresh token")
		return
	}
	if err := s.store.SaveRefreshToken(r.Context(), refreshHash, store.RefreshToken{
		ClientID: client.ClientID,
		UserID:   user.ID,
		Scopes:   scopes,
	}, now.Add(s.refreshTTL)); err != nil {
		s.log.Error("save refresh token", "error", err)
		oauthError(w, http.StatusInternalServerError, "server_error", "could not issue a refresh token")
		return
	}
	body["refresh_token"] = refreshToken

	if containsScope(scopes, "openid") {
		idToken, err := s.keys.Sign(tokens.Claims{
			Issuer:        s.cfg.Server.Issuer,
			Subject:       subject,
			Audience:      client.ClientID,
			IssuedAt:      now.Unix(),
			ExpiresAt:     now.Add(s.accessTTL).Unix(),
			TokenType:     "id",
			Nonce:         nonce,
			Name:          user.Name,
			Email:         user.Email,
			EmailVerified: true,
			Picture:       user.AvatarURL,
		})
		if err != nil {
			s.log.Error("sign id token", "error", err)
			oauthError(w, http.StatusInternalServerError, "server_error", "could not sign an id token")
			return
		}
		body["id_token"] = idToken
	}
	writeJSON(w, http.StatusOK, body)
}

func containsScope(scopes []string, want string) bool {
	for _, s := range scopes {
		if s == want {
			return true
		}
	}
	return false
}

// ---------------------------------------------------------------- introspect / revoke

func (s *Server) handleIntrospect(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseForm(); err != nil {
		oauthError(w, http.StatusBadRequest, "invalid_request", "malformed form body")
		return
	}
	if _, err := s.authenticateClient(r); err != nil {
		w.Header().Set("WWW-Authenticate", `Basic realm="nabuauth"`)
		oauthError(w, http.StatusUnauthorized, "invalid_client", err.Error())
		return
	}
	claims, err := s.keys.Verify(r.PostFormValue("token"))
	if err != nil || claims.Issuer != s.cfg.Server.Issuer {
		// RFC 7662: an unusable token is reported as inactive, not as an error.
		writeJSON(w, http.StatusOK, map[string]any{"active": false})
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{
		"active":    true,
		"sub":       claims.Subject,
		"aud":       claims.Audience,
		"client_id": claims.ClientID,
		"scope":     claims.Scope,
		"exp":       claims.ExpiresAt,
		"iat":       claims.IssuedAt,
		"token_use": claims.TokenType,
	})
}

func (s *Server) handleRevoke(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseForm(); err != nil {
		oauthError(w, http.StatusBadRequest, "invalid_request", "malformed form body")
		return
	}
	if _, err := s.authenticateClient(r); err != nil {
		w.Header().Set("WWW-Authenticate", `Basic realm="nabuauth"`)
		oauthError(w, http.StatusUnauthorized, "invalid_client", err.Error())
		return
	}
	if token := r.PostFormValue("token"); token != "" {
		if err := s.store.RevokeRefreshToken(r.Context(), tokens.HashOpaque(token)); err != nil {
			s.log.Error("revoke token", "error", err)
		}
	}
	// Always 200: revocation of an unknown token is a success by definition.
	w.WriteHeader(http.StatusOK)
}

func (s *Server) handleLogout(w http.ResponseWriter, r *http.Request) {
	s.endSession(w, r)
	redirect := r.URL.Query().Get("post_logout_redirect_uri")
	if redirect == "" {
		http.Redirect(w, r, "/login", http.StatusFound)
		return
	}
	// Only bounce to a URI some registered app actually owns; an open redirect
	// here would be handed to every phishing attempt in the ecosystem.
	if !s.isRegisteredOrigin(r.Context(), redirect) {
		s.render(w, http.StatusBadRequest, "error.html", map[string]any{
			"Title":   "Redirect not allowed",
			"Message": "post_logout_redirect_uri must belong to a registered Nabu application.",
		})
		return
	}
	http.Redirect(w, r, redirect, http.StatusFound)
}

// isRegisteredOrigin reports whether a URL shares an origin with a registered
// app URL or redirect URI.
func (s *Server) isRegisteredOrigin(ctx context.Context, raw string) bool {
	target, err := url.Parse(raw)
	if err != nil || target.Scheme == "" || target.Host == "" {
		return false
	}
	clients, err := s.store.ListedClients(ctx)
	if err != nil {
		return false
	}
	for _, c := range clients {
		candidates := append([]string{c.AppURL}, c.RedirectURIs...)
		for _, cand := range candidates {
			u, err := url.Parse(cand)
			if err != nil {
				continue
			}
			if u.Scheme == target.Scheme && strings.EqualFold(u.Host, target.Host) {
				return true
			}
		}
	}
	return false
}
