// Package tokens signs and verifies the RS256 JWTs NabuAuth issues, and
// publishes the matching JWKS so ecosystem apps can verify offline.
package tokens

import (
	"crypto"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/subtle"
	"crypto/x509"
	"encoding/base64"
	"encoding/binary"
	"encoding/json"
	"encoding/pem"
	"errors"
	"fmt"
	"strings"
	"time"
)

// ErrInvalidToken covers every verification failure. The caller only ever needs
// to know the token is not usable — telling a client *why* helps an attacker
// more than it helps a developer.
var ErrInvalidToken = errors.New("invalid token")

// Keyring holds the active signing key and every key still trusted for
// verification.
type Keyring struct {
	signKID string
	signKey *rsa.PrivateKey
	verify  map[string]*rsa.PublicKey
}

// NewKeyring builds a keyring from PEM-encoded PKCS#8 private keys, newest
// first. The first key signs; all of them verify.
func NewKeyring(keys []struct{ KID, PEM string }) (*Keyring, error) {
	if len(keys) == 0 {
		return nil, errors.New("no signing keys")
	}
	kr := &Keyring{verify: map[string]*rsa.PublicKey{}}
	for i, k := range keys {
		priv, err := parsePrivateKey(k.PEM)
		if err != nil {
			return nil, fmt.Errorf("parse signing key %s: %w", k.KID, err)
		}
		if i == 0 {
			kr.signKID, kr.signKey = k.KID, priv
		}
		kr.verify[k.KID] = &priv.PublicKey
	}
	return kr, nil
}

// GenerateKey creates a fresh RSA key and returns its id and PKCS#8 PEM.
func GenerateKey() (kid, pemStr string, err error) {
	priv, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return "", "", err
	}
	der, err := x509.MarshalPKCS8PrivateKey(priv)
	if err != nil {
		return "", "", err
	}
	pemStr = string(pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: der}))
	// The key id is derived from the public key, so the same key always gets the
	// same id no matter which replica loads it.
	pub, err := x509.MarshalPKIXPublicKey(&priv.PublicKey)
	if err != nil {
		return "", "", err
	}
	sum := sha256.Sum256(pub)
	return base64.RawURLEncoding.EncodeToString(sum[:8]), pemStr, nil
}

func parsePrivateKey(pemStr string) (*rsa.PrivateKey, error) {
	block, _ := pem.Decode([]byte(pemStr))
	if block == nil {
		return nil, errors.New("not a PEM block")
	}
	if key, err := x509.ParsePKCS8PrivateKey(block.Bytes); err == nil {
		rsaKey, ok := key.(*rsa.PrivateKey)
		if !ok {
			return nil, errors.New("signing key is not RSA")
		}
		return rsaKey, nil
	}
	// Accept PKCS#1 too, so an operator can paste a key generated by openssl's
	// older default without it silently failing at boot.
	return x509.ParsePKCS1PrivateKey(block.Bytes)
}

// Claims is the payload NabuAuth puts in access and identity tokens.
type Claims struct {
	Issuer    string `json:"iss"`
	Subject   string `json:"sub"`
	Audience  string `json:"aud,omitempty"`
	ExpiresAt int64  `json:"exp"`
	IssuedAt  int64  `json:"iat"`
	NotBefore int64  `json:"nbf,omitempty"`
	JTI       string `json:"jti,omitempty"`

	// TokenType separates an access token from an id_token, so an id_token can
	// never be presented as a bearer credential.
	TokenType string `json:"typ,omitempty"`
	ClientID  string `json:"client_id,omitempty"`
	Scope     string `json:"scope,omitempty"`

	Name          string `json:"name,omitempty"`
	Email         string `json:"email,omitempty"`
	EmailVerified bool   `json:"email_verified,omitempty"`
	Picture       string `json:"picture,omitempty"`
	Nonce         string `json:"nonce,omitempty"`
}

// Scopes splits the space-delimited scope claim.
func (c Claims) Scopes() []string { return strings.Fields(c.Scope) }

// HasScope reports whether the token carries a scope.
func (c Claims) HasScope(scope string) bool {
	for _, s := range c.Scopes() {
		if s == scope {
			return true
		}
	}
	return false
}

// Sign returns a compact RS256 JWT for the claims.
func (kr *Keyring) Sign(c Claims) (string, error) {
	header, err := json.Marshal(map[string]string{"alg": "RS256", "typ": "JWT", "kid": kr.signKID})
	if err != nil {
		return "", err
	}
	payload, err := json.Marshal(c)
	if err != nil {
		return "", err
	}
	enc := base64.RawURLEncoding
	signingInput := enc.EncodeToString(header) + "." + enc.EncodeToString(payload)
	sum := sha256.Sum256([]byte(signingInput))
	sig, err := rsa.SignPKCS1v15(rand.Reader, kr.signKey, crypto.SHA256, sum[:])
	if err != nil {
		return "", err
	}
	return signingInput + "." + enc.EncodeToString(sig), nil
}

// Verify checks the signature and the time window, and returns the claims.
func (kr *Keyring) Verify(token string) (Claims, error) {
	parts := strings.Split(token, ".")
	if len(parts) != 3 {
		return Claims{}, ErrInvalidToken
	}
	enc := base64.RawURLEncoding
	rawHeader, err := enc.DecodeString(parts[0])
	if err != nil {
		return Claims{}, ErrInvalidToken
	}
	var header struct {
		Alg string `json:"alg"`
		KID string `json:"kid"`
	}
	if err := json.Unmarshal(rawHeader, &header); err != nil {
		return Claims{}, ErrInvalidToken
	}
	// Pin the algorithm. Trusting the header's alg is the classic JWT hole: a
	// token claiming "none" or a symmetric alg must not be accepted here.
	if header.Alg != "RS256" {
		return Claims{}, ErrInvalidToken
	}
	pub, ok := kr.verify[header.KID]
	if !ok {
		return Claims{}, ErrInvalidToken
	}
	sig, err := enc.DecodeString(parts[2])
	if err != nil {
		return Claims{}, ErrInvalidToken
	}
	sum := sha256.Sum256([]byte(parts[0] + "." + parts[1]))
	if err := rsa.VerifyPKCS1v15(pub, crypto.SHA256, sum[:], sig); err != nil {
		return Claims{}, ErrInvalidToken
	}
	rawPayload, err := enc.DecodeString(parts[1])
	if err != nil {
		return Claims{}, ErrInvalidToken
	}
	var c Claims
	if err := json.Unmarshal(rawPayload, &c); err != nil {
		return Claims{}, ErrInvalidToken
	}
	now := time.Now().Unix()
	// 60s of leeway: clocks between the gateway, the apps and this server drift,
	// and a token rejected one second early looks like a random logout.
	const leeway = 60
	if c.ExpiresAt != 0 && now > c.ExpiresAt+leeway {
		return Claims{}, ErrInvalidToken
	}
	if c.NotBefore != 0 && now < c.NotBefore-leeway {
		return Claims{}, ErrInvalidToken
	}
	return c, nil
}

// JWKS renders the public keys as a JSON Web Key Set.
func (kr *Keyring) JWKS() map[string]any {
	keys := make([]map[string]string, 0, len(kr.verify))
	for kid, pub := range kr.verify {
		eBytes := make([]byte, 8)
		binary.BigEndian.PutUint64(eBytes, uint64(pub.E))
		eBytes = trimLeadingZeros(eBytes)
		keys = append(keys, map[string]string{
			"kty": "RSA",
			"use": "sig",
			"alg": "RS256",
			"kid": kid,
			"n":   base64.RawURLEncoding.EncodeToString(pub.N.Bytes()),
			"e":   base64.RawURLEncoding.EncodeToString(eBytes),
		})
	}
	return map[string]any{"keys": keys}
}

func trimLeadingZeros(b []byte) []byte {
	for i, v := range b {
		if v != 0 {
			return b[i:]
		}
	}
	return []byte{0}
}

// SigningKID reports which key is currently signing, for logs and diagnostics.
func (kr *Keyring) SigningKID() string { return kr.signKID }

// ---------------------------------------------------------------- opaque tokens

// NewOpaque returns a high-entropy random token, and the SHA-256 hash under
// which it should be stored. Only the hash is persisted, so a database leak
// cannot be replayed against the token endpoint.
func NewOpaque() (token, hash string, err error) {
	buf := make([]byte, 32)
	if _, err := rand.Read(buf); err != nil {
		return "", "", err
	}
	token = base64.RawURLEncoding.EncodeToString(buf)
	return token, HashOpaque(token), nil
}

// HashOpaque hashes an opaque token for storage or lookup.
func HashOpaque(token string) string {
	sum := sha256.Sum256([]byte(token))
	return base64.RawURLEncoding.EncodeToString(sum[:])
}

// VerifyPKCE checks an RFC 7636 code_verifier against the stored challenge.
func VerifyPKCE(challenge, method, verifier string) bool {
	if challenge == "" {
		return verifier == ""
	}
	if verifier == "" {
		return false
	}
	switch method {
	case "S256", "":
		sum := sha256.Sum256([]byte(verifier))
		want := base64.RawURLEncoding.EncodeToString(sum[:])
		return subtle.ConstantTimeCompare([]byte(want), []byte(challenge)) == 1
	case "plain":
		return subtle.ConstantTimeCompare([]byte(verifier), []byte(challenge)) == 1
	default:
		return false
	}
}
